theme = 'hugo-paper'

baseURL = 'https://chalamov.dev/'
languageCode = 'en-us'
title = 'Vidol Chalamov'

# disqusShortname = 'YOUR_DISQUS_SHORTNAME' # use disqus comments

[params]
# color style
color = 'linen' # linen, wheat, gray, light

# header social icons
github = 'vidolch'     # github.com/YOUR_GITHUB_ID
instagram = 'vidol_ch' # instagram.com/YOUR_INSTAGRAM_ID
linkedin = 'vidolch'   # linkedin.com/in/YOUR_LINKEDIN_ID
# rss = true             # show rss icon

# home page profile
avatar = 'vidolch@gmail.com' # gravatar email or image url
name = 'Vidol Chalamov'
# bio = 'YOUR_BIO'


# misc
# disableHLJS = true                        # disable highlight.js
# disablePostNavigation = true              # disable post navigation
# monoDarkIcon = true                       # show monochrome dark mode icon
# gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
# graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
# math = true                               # enable KaTeX math typesetting globally

# giscus
# [params.giscus]
#   repo = 'YOUR_GISCUS_REPO'                 # see https://giscus.app for more details
#   repoId = 'YOUR_GISCUS_REPO_ID'
#   category = 'YOUR__GISCUS_CATEGORY'
#   categoryId = 'YOUR_GISCUS_CATEGORY_ID'
#   mapping = 'pathname'
#   theme = 'light'
#   lang = 'zh-CN'

[menu]

  [[menu.main]]
    identifier = "about-me"
    name = "About me"
    url = "/about-me/"
